version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    hostname: localstack
    ports:
      - "4572:4572"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST:unix:///var/run/docker.sock
    volumes:
      #- "${PWD}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend
networks: 
  backend:
    driver: 'bridge'
 